### ISSUE TITLE
"para" sRGB-v4.icc g value should be 2.399994 not 2.400040

### ISSUE THREAD

**Issue by ValZapod** [saucecontrol/Compact-ICC-Profiles#6]
See apple's profile: 

I used ICC profile Inspector to check.
[2020_iPhone_0233_2020_06_14.icc.txt](https://github.com/saucecontrol/Compact-ICC-Profiles/files/7164691/2020_iPhone_0233_2020_06_14.icc.txt) (remove txt extension)

Other values (a, b, c, d) are correct.

As far as I understand the value is rounded and here Apple profile actually looks worse, so maybe it is a bug. Or maybe it is not rounded but float redistributed in which case -6 is better than +40. From the spec it is kinda both, but all that special nonstandard float represention is above my head.

**Comment by saucecontrol** [comment]
Yeah, that's intentional. The basic idea is that when quantized to 16 bits for the profile representation, both the `a` and `g` values round down, which amplifies the error. Rounding the `g` value up instead of down results in a curve that matches the actual sRGB curve more closely.

See the first section of [this post](https://photosauce.net/blog/post/making-a-minimal-srgb-icc-profile-part-4-final-results) for more detail.

**Comment by ValZapod** [comment]
Do you think Applema de a mistake then?

**Comment by saucecontrol** [comment]
No, I wouldn't say it's a mistake. If you take the true values from the sRGB curve and convert them individually to ICC s15Fixed16 format with natural rounding, you get the values Apple used. However, because the values represent a complex curve, it turns out that by adjusting that `g` value up slightly, you can match the original curve more closely.

I happen to have noticed that trick because I had been doing some detailed analysis of the curve's error and found a better fit than the naive rounding. The question comes down to whether it's better to match Apple's profile value or the intended value, and I chose to side with the intended curve.

**Comment by ValZapod** [comment]
SMPTE RP 177 and its part on renormalisation is what defines how IEC derived its 4 decimal sRGB XYZ matrices and 7 decimal inverted from 4 decimal sYCC XYZ matrices. I read your whole blog, inlcuding on "chad" and sRGB (https://photosauce.net/blog/post/what-makes-srgb-a-special-color-space), and I do agree with you, not with those: https://discuss.pixls.us/t/feature-request-save-as-floating-point/5696/190 But to say it is slightly not BT.709 or D65 is misleading, since that is just how RP 177 works. Same happens with YCbCr BT.2020: you are inverting the very same 4 decimal points R'G'B' to Y'Cb'Cr' matrix, just with higher precision. That way the highest precision is RGB or R'G'B' data.
