### ISSUE TITLE
P3-500 nits 2.2 or srgb trc?

### ISSUE THREAD

**Issue by 24fpsDaVinci** [saucecontrol/Compact-ICC-Profiles#8]
the new M1/2 gen laptops and studio display uses a default P3-500nits profile; does the new profile still use the same srgb trc as old the intel mac P3 profiles? Would you be able to include the new profile? Apple seems to have changed the factory calibration on these macs to 2.2 whereas the old macs had a custom curve. 

left is the P3-v4 profile with srgb trc, right is the edid from studio display, the primaries are still p3 but trc shows 2.2

![Screenshot from 2022-10-02 11-50-36](https://user-images.githubusercontent.com/3499141/193463315-9f85b5e5-8615-443d-b869-9960d792f2fc.png)

**Comment by saucecontrol** [comment]
Weird, it looks like the display profile has the blue and green primaries swapped as well.  I don't have access to any mac hardware, so I don't really have a way to get the profile or to test.  Have you seen cases where that display profile is attached to image files?  If so, can you share one?

**Comment by 24fpsDaVinci** [comment]
I also dont own mac hardware except the display. I was able to verify the profiles are still using srgb trc after downloading one from a m1 macbook pro at the store. But the displays are now calibrated to 2.2; at least in the default p3-500 mode, I checked using a colorimeter.
[StudioDisplayICC.zip](https://github.com/saucecontrol/Compact-ICC-Profiles/files/9700036/StudioDisplayICC.zip)
![Screenshot from 2022-10-03 14-22-28](https://user-images.githubusercontent.com/3499141/193651828-078c4fb0-40de-4ab5-a08e-f1f2015e739c.png)

**Comment by saucecontrol** [comment]
That seems normal to me.  Going back to the CRT days, displays have always had a power law response, and 2.2 gamma is the basis of sRGB (the 2.4 power value used in sRGB is offset and scaled such that it very closely matches gamma 2.2).  The main reason sRGB differs from pure gamma 2.2 is that the values too quickly approach zero on the bottom end, so when values are quantized to 8 bits, too many of them crush to zero.  The piecewise sRGB curve is compensating for that but can otherwise be considered to be nominally gamma 2.2.
