### ISSUE TITLE
how to generate my own profile?

### ISSUE THREAD

**Issue by 24fpsDaVinci** [saucecontrol/Compact-ICC-Profiles#9]
how can i generate similar profiles with custom RGB values? the few programs ive tried dont create the same tags, for example chad is missing. the custom 2.4 trc i also cant seem to duplicate so resorting to copy and pasting. is there a particular program I can use?

**Comment by saucecontrol** [comment]
I don't know of any existing programs, unfortunately.  I created all the profiles in this repo by hand in a hex editor, although I do have a couple of quick-and-dirty utilities I wrote to generate the tag values.  I have a full generator on my weekend project list for when I get some spare time.  I actually made some progress on that recently since I needed some of the same code for another project.  I'll update here when I get that done.

**Comment by saucecontrol** [comment]
Closing this since #1 is already tracking the generator
